steps:
  - label: ":docker: Build and Upload Artifact"
    plugins:
      docker-compose#v3.7.0:
        run: web
    artifact_paths:
      - hello

  - block: "Enter your name"
    key: "name-input"

  - label: ":bash: Run Compiled Program"
    command: "./hello $(buildkite-agent meta-data get user-name)"
    depends_on: "name-input"
    artifact_paths:
      - hello

  - wait

  - label: ":package: Save Metadata"
    command: buildkite-agent meta-data set user-name "{your name}"
