steps:
  - label: ":mag: List directory contents"
    command: |
      echo "Current directory:"
      pwd
      echo "Directory contents:"
      ls -la
      echo "Contents of hello directory:"
      ls -la hello/

  - label: ":docker: Build and Upload"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.21.0"
          workdir: /go/src/app
          volumes:
            - .:/go/src/app
          environment:
            - BUILDKITE_AGENT_ACCESS_TOKEN
          command: [
              "/bin/sh",
              "-c",
              "
              cd hello &&
              go build -v -o hello &&
              mkdir -p artifact &&
              mv hello artifact/ &&
              buildkite-agent artifact upload 'artifact/**/*'
              ",
            ]
            
  - block: "Enter your name"
    key: "name-input"

  - label: ":bash: Run Compiled Program"
    command: "./hello $(buildkite-agent meta-data get user-name)"
    depends_on: "name-input"
    artifact_paths:
      - hello

  - wait

  - label: ":package: Save Metadata"
    command: buildkite-agent meta-data set user-name "{your name}"
